version: '3'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
       POSTGRES_DB: 'hello'
       POSTGRES_USER: 'guilherme'
       POSTGRES_PASSWORD: '123456'
    # volumes:
    #   - /root/postgres:/var/lib/postgresql/data

  web:
    image: hello
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
