apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "hello-ingress"
  namespace: "hello-app"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
  labels:
    app: hello-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "service-hello"
              servicePort: 80
