apiVersion: apps/v1
kind: Deployment
metadata:
  name: "hello-deployment"
  namespace: "hello-app"
spec:
  selector:
    matchLabels:
      app: "hello"
  replicas: 4
  template:
    metadata:
      labels:
        app: "hello"
    spec:
      containers:
      - image: 324382802360.dkr.ecr.eu-west-1.amazonaws.com/ecr-gui:3.0
        imagePullPolicy: Always
        name: "hello"
        ports:
        - containerPort: 8000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
